Update githubaction

diff --git a/githubaction b/githubaction
--- a/githubaction
+++ b/githubaction
@@ -1,87 +1,84 @@
-name: Config_graph_Web_App
+name: orx-cwp-config-service-webapp
+
 on:
-  pull_request:
-  workflow_dispatch: 
+  push:
+    branches:
+      - 'master'
+  workflow_run:
+    workflows: [quality-checks]
+    types:
+      - completed
+  workflow_dispatch:
     inputs:
-     environment:
-       description: 'CWP Environment'
-       type: choice
-       options:
-          - dev
-          - stg
-          - prf
-          - tst
-     region:
-        description: CWP Region
-        type: choice
+      environment:
+        description: 'Select Environment'
+        required: true
+        # default: 'dev'
         options:
-           - central
-           - east
-           - both
+          - dev
+          - tst
+          - prf
+          - stg
+
 jobs:
   BuildandDeploy:
-     name: 'Build and Deployment' 
-     runs-on: [uhg-runner]
-     steps: 
-       - name: Checkout Repository
-         uses: actions/checkout@v3.5.3
-         with:
-           repository: ${{github.repository}}
-           
-       - name: Login to Azure
-         uses: azure/login@v1
-         continue-on-error: false
-         with:
-          creds: ${{ secrets.SERVICEPRINCIPAL }}
-          
-       - name: Setup Node.js environment
-         uses: actions/setup-node@v2.5.2
-         with:
-            always-auth: false
-            node-version: 16.19.1 
-       - name: Install Dependencies
-         run: yarn install
+    name: 'Build and Deployment'
+    runs-on: [uhg-runner]
 
-       - name: Run quality checks for Pull Requests
-         run: |
-                yarn check-types
-                yarn format:check
-                echo "===== Running lint ====="
-                yarn lint
-       - name: Build WebApp
-         run: yarn build
-       - name: Install Prod Dependencies
-         run: yarn workspaces focus --production
-       - name: Copy Prod Files
-         uses: actions/upload-artifact@v2
-         with:
-            name: drop
-            path: |
-              .yarn/**
-              .next/**
-              .yarnrc.yml
-               yarn.lock
-               node_modules/**
-               public/**
-               package.json
-               ecosystem.config.js
-               next.config.js
-       - name: Archive Prod Files
-         run: |
-            cd ${{ github.workspace }}
-            zip -r $(Build.BuildId).zip .
-       - name: Publish Prod Files
-         uses: actions/upload-artifact@v2
-         with:
-            name: drop
-            path: ${{ github.workspace }}/*.zip      
-       - name: Azure WebApp
-         uses: Azure/webapps-deploy@v2.2.10
-         with:
-      # Name of the Azure Web App
-            app-name: 'mbr-portal-cfga-${{ ENV.environment }}-us-c-webapp'
-            publish-profile: ${{ secrets.AzureAppService_PublishProfile_a5651b38972e4899b92de9bf50e16862 }}
-            slot-name: 'production' 
-            package: '$(Build.ArtifactStagingDirectory)/**/*.zip'
-            startup-command: 'yarn start'
-            resource-group-name: 'mbr-portal-${{ ENV.environment }}-us-c-rg'
+    steps:
+      - name: Set App Name
+        id: set_app_name
+        run: echo "::set-output name=app_name::mbr-${{ inputs.environment }}"
+
+      - name: Set Publish Profile Secret
+        id: set_publish_profile_secret
+        run: |
+          if [[ "${{ inputs.environment }}" == 'dev' ]]; then
+            echo "::set-output name=publish_profile_secret::${{ secrets.DEV_AZURE_WEBAPP_PUBLISH_PROFILE }}"
+          elif [[ "${{ inputs.environment }}" == 'tst' ]]; then
+            echo "::set-output name=publish_profile_secret::${{ secrets.TST_AZURE_WEBAPP_PUBLISH_PROFILE }}"
+          elif [[ "${{ inputs.environment }}" == 'prf' ]]; then
+            echo "::set-output name=publish_profile_secret::${{ secrets.PRF_AZURE_WEBAPP_PUBLISH_PROFILE }}"
+          elif [[ "${{ inputs.environment }}" == 'stg' ]]; then
+            echo "::set-output name=publish_profile_secret::${{ secrets.STG_AZURE_WEBAPP_PUBLISH_PROFILE }}"
+          else
+            echo "Invalid environment selected"
+            exit 1
+          fi
+
+      - name: setup
+        uses: optum-rx-consumer-digital/orx-cwp-config-service-webapp/.github/actions/setup@master
+        with:
+          repository: ${{ github.repository }}
+
+      - name: Production Build
+        run: yarn build
+
+      - name: Install Prod Dependencies
+        run: yarn workspaces focus --production
+
+      - name: Copy Prod Files
+        run: |
+          mkdir -p ${{ github.workspace }}/cfga_webapp
+          cp -rvf .yarn '${{ github.workspace }}/cfga_webapp'
+          cp -rvf .next '${{ github.workspace }}/cfga_webapp'
+          cp -rvf yarn.lock '${{ github.workspace }}/cfga_webapp'
+          cp -rvf node_modules '${{ github.workspace }}/cfga_webapp'
+          cp -rvf public '${{ github.workspace }}/cfga_webapp'
+          cp -rvf package.json '${{ github.workspace }}/cfga_webapp'
+          cp -rvf ecosystem.config.js '${{ github.workspace }}/cfga_webapp'
+          cp -rvf next.config.js '${{ github.workspace }}/cfga_webapp'
+
+      - name: Login to Azure
+        uses: azure/login@v1
+        continue-on-error: false
+        with:
+          creds: ${{ secrets.SERVICEPRINCIPAL }}
+
+      - name: Azure WebApp
+        uses: Azure/webapps-deploy@v2
+        with:
+          app-name: ${{ steps.set_app_name.outputs.app_name }}-us-c-webapp
+          slot-name: 'production'
+          package: '${{ github.workspace }}/cfga_webapp/'
+          publish-profile: ${{ steps.set_publish_profile_secret.outputs.publish_profile_secret }}
